FROM python:3.10.1

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY main.py main.py 
COPY config_variables.py config_variables.py 
COPY credentials.json credentials.json

ENTRYPOINT [ "python", "main.py" ]