### Docker Compose 

version: '3'
services:
  data-ingester:
    build:
      context: ./data_ingester/
      dockerfile: Dockerfile-ingester
    volumes:
      - "../data/raw/:/app/data/raw:rw"



  