version: 2

sources:
  - name: staging 
    database: pipelineproject01
    schema: pipelineproject01_spark

    tables:
      - name: 2015-data
      - name: 2016-data
      - name: 2017-data
      - name: 2018-data
      - name: 2019-data
      - name: 2020-data
      - name: 2021-data

